//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AirlineDatabaseEntities : DbContext
    {
        public AirlineDatabaseEntities()
            : base("name=AirlineDatabaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Вход> Вход { get; set; }
        public virtual DbSet<Заявка> Заявка { get; set; }
        public virtual DbSet<Полет> Полет { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Постоянный_клиент> Постоянный_клиент { get; set; }
        public virtual DbSet<Рейс> Рейс { get; set; }
    
        public virtual ObjectResult<Nullable<int>> Insert_User(string login, string password, string name, string surname, string thirdname)
        {
            var loginParameter = login != null ?
                new ObjectParameter("login", login) :
                new ObjectParameter("login", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var surnameParameter = surname != null ?
                new ObjectParameter("surname", surname) :
                new ObjectParameter("surname", typeof(string));
    
            var thirdnameParameter = thirdname != null ?
                new ObjectParameter("thirdname", thirdname) :
                new ObjectParameter("thirdname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Insert_User", loginParameter, passwordParameter, nameParameter, surnameParameter, thirdnameParameter);
        }
    
        public virtual ObjectResult<LoginByPassword_Result> LoginByPassword(string login, string pass)
        {
            var loginParameter = login != null ?
                new ObjectParameter("login", login) :
                new ObjectParameter("login", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoginByPassword_Result>("LoginByPassword", loginParameter, passParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> LoginByPassword1(string login, string pass)
        {
            var loginParameter = login != null ?
                new ObjectParameter("login", login) :
                new ObjectParameter("login", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("LoginByPassword1", loginParameter, passParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> LoginByPassword2(string login, string pass)
        {
            var loginParameter = login != null ?
                new ObjectParameter("login", login) :
                new ObjectParameter("login", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("LoginByPassword2", loginParameter, passParameter);
        }
    }
}
