//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline.Models
{
    using System;
	using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;

    public partial class Заявка
    {
        [Required]
        public int id { get; set; }
        [Required]
        public int id_клиента { get; set; }
        [Required]
        public int id_полета { get; set; }
        [Required]
        public string Класс { get; set; }
        [Required]
        [Range(1, 9, ErrorMessage = "Можно забронировать только от 1 до 9 билетов")]
        public int Количество_мест { get; set; }
        public decimal Сумма { get; set; }
        public Nullable<int> Премиальные_очки { get; set; }
    
        public virtual Полет Полет { get; set; }
        public virtual Пользователи Пользователи { get; set; }
    }
}
