//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

    public partial class Полет
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Полет()
        {
            this.Заявка = new HashSet<Заявка>();
        }
    
        public int id { get; set; }
        public int id_рейса { get; set; }
        public System.DateTime Дата { get; set; }
        [Display(Name = "Количество мест в эконом классе")]
        public int Места_эконом { get; set; }
        [Display(Name = "Стоимость мест в эконом классе")]
        public decimal Стоимость_эконом { get; set; }
        [Display(Name = "Количество мест в vip классе")]
        public int Места_vip { get; set; }
        [Display(Name = "Стоимость мест в vip классе")]
        public decimal Стоимость_vip { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заявка> Заявка { get; set; }
        public virtual Рейс Рейс { get; set; }
    }
}
